-- MySQL Script generated by MySQL Workbench
-- Thu Feb 14 10:54:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_almoxarifado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_almoxarifado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_almoxarifado` DEFAULT CHARACTER SET latin1 ;
USE `db_almoxarifado` ;

-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblacesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblacesso` (
  `intacessoid` INT(11) NOT NULL AUTO_INCREMENT,
  `stracesso` VARCHAR(45) NOT NULL,
  `strdescricao` VARCHAR(255) NULL DEFAULT NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`intacessoid`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`users` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `intacessoid` INT(10) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `usuario` VARCHAR(191) NOT NULL,
  `password` VARCHAR(191) NOT NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '1',
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`usuario` ASC) VISIBLE,
  INDEX `fk_user_acesso` (`intacessoid` ASC) VISIBLE,
  CONSTRAINT `fk_user_acesso`
    FOREIGN KEY (`intacessoid`)
    REFERENCES `db_almoxarifado`.`tblacesso` (`intacessoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblatividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblatividade` (
  `intatividadeid` INT(11) NOT NULL AUTO_INCREMENT,
  `intusuarioid` INT(11) NOT NULL,
  `stratividade` VARCHAR(45) NOT NULL,
  `strtipoatividade` VARCHAR(45) NULL DEFAULT NULL,
  `datinicial` DATE NOT NULL,
  `datfinal` DATE NOT NULL,
  `datvalidade` DATE NULL DEFAULT NULL,
  `timcargahoraria` TIME NOT NULL,
  `bolstatus` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`intatividadeid`),
  INDEX `fk_ativ_usuario_idx` (`intusuarioid` ASC) VISIBLE,
  CONSTRAINT `fk_ativ_usuario`
    FOREIGN KEY (`intusuarioid`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblcargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblcargo` (
  `intcargoid` INT(11) NOT NULL AUTO_INCREMENT,
  `strcargo` VARCHAR(45) NOT NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`intcargoid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblcategoria` (
  `intcategoriaid` INT(11) NOT NULL AUTO_INCREMENT,
  `strcategoria` VARCHAR(45) NOT NULL,
  `strdescricao` VARCHAR(255) NULL DEFAULT NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`intcategoriaid`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblterceirizada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblterceirizada` (
  `intterceirizadaid` INT NOT NULL AUTO_INCREMENT,
  `strnome_empresa` VARCHAR(255) NOT NULL,
  `strcnpj` VARCHAR(20) NOT NULL,
  `strtipo_servico` VARCHAR(45) NOT NULL,
  `strendereco` VARCHAR(255) NULL,
  `strcep` VARCHAR(12) NULL,
  `strtelefone` VARCHAR(15) NULL,
  `strbairro` VARCHAR(45) NULL,
  `strcidade` VARCHAR(45) NULL,
  `charuf` CHAR(2) NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`intterceirizadaid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblcontato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblcontato` (
  `intcontatoid` INT(11) NOT NULL AUTO_INCREMENT,
  `intterceirizadaid` INT(11) NOT NULL,
  `strcontato` VARCHAR(191) NOT NULL,
  `strtelefone` VARCHAR(15) NOT NULL,
  `strfuncao` VARCHAR(45) NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`intcontatoid`),
  INDEX `fk_terc_contato_idx` (`intterceirizadaid` ASC) VISIBLE,
  CONSTRAINT `fk_terc_contato`
    FOREIGN KEY (`intterceirizadaid`)
    REFERENCES `db_almoxarifado`.`tblterceirizada` (`intterceirizadaid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblfuncionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblfuncionario` (
  `intfuncionarioid` INT(11) NOT NULL AUTO_INCREMENT,
  `intcargoid` INT(11) NOT NULL,
  `intmatricula` INT(6) NOT NULL,
  `strnome` VARCHAR(255) NOT NULL,
  `datnascimento` DATE NOT NULL,
  `datadmissao` DATE NOT NULL,
  `bolstatus` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`intfuncionarioid`),
  INDEX `fk_func_cargo_idx` (`intcargoid` ASC) VISIBLE,
  CONSTRAINT `fk_func_cargo`
    FOREIGN KEY (`intcargoid`)
    REFERENCES `db_almoxarifado`.`tblcargo` (`intcargoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tbldetalhesatividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tbldetalhesatividade` (
  `intdetalhesatividadeid` INT(11) NOT NULL AUTO_INCREMENT,
  `intatividadeid` INT(11) NOT NULL,
  `intfuncionarioid` INT(11) NOT NULL,
  PRIMARY KEY (`intdetalhesatividadeid`),
  INDEX `fk_detatv_func_idx` (`intfuncionarioid` ASC) VISIBLE,
  INDEX `fk_det_atv_idx` (`intatividadeid` ASC) VISIBLE,
  CONSTRAINT `fk_det_atv`
    FOREIGN KEY (`intatividadeid`)
    REFERENCES `db_almoxarifado`.`tblatividade` (`intatividadeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detatv_func`
    FOREIGN KEY (`intfuncionarioid`)
    REFERENCES `db_almoxarifado`.`tblfuncionario` (`intfuncionarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblfornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblfornecedor` (
  `intfornecedorid` INT(11) NOT NULL AUTO_INCREMENT,
  `strfornecedor` VARCHAR(50) NOT NULL,
  `strcnpj` VARCHAR(18) NOT NULL,
  `stremail` VARCHAR(191) NULL DEFAULT NULL,
  `strendereco` VARCHAR(255) NULL DEFAULT NULL,
  `strbairro` VARCHAR(45) NULL DEFAULT NULL,
  `strcep` VARCHAR(9) NULL DEFAULT NULL,
  `strtelefone` VARCHAR(16) NULL DEFAULT NULL,
  `strcidade` VARCHAR(45) NULL DEFAULT NULL,
  `charuf` CHAR(2) NULL DEFAULT NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`intfornecedorid`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblnotaentrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblnotaentrada` (
  `intnotaentradaid` INT(11) NOT NULL AUTO_INCREMENT,
  `intfornecedorid` INT(11) NOT NULL,
  `intusuarioid` INT(11) NOT NULL,
  `intnumnota` INT(11) UNSIGNED ZEROFILL NOT NULL,
  `datentrada` DATETIME NOT NULL,
  `dblfrete` DECIMAL(7,2) NULL,
  `dbldesconto` DECIMAL(7,2) NULL,
  `dbltotal` DECIMAL(7,2) NOT NULL,
  `bolstatus` CHAR(1) NOT NULL DEFAULT 'R',
  `strnatureza` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`intnotaentradaid`),
  INDEX `fk_entrada_forn_idx` (`intfornecedorid` ASC) VISIBLE,
  INDEX `fk_entrada_user_idx` (`intusuarioid` ASC) VISIBLE,
  UNIQUE INDEX `intnumnota_UNIQUE` (`intnumnota` ASC) VISIBLE,
  CONSTRAINT `fk_entrada_forn`
    FOREIGN KEY (`intfornecedorid`)
    REFERENCES `db_almoxarifado`.`tblfornecedor` (`intfornecedorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrada_user`
    FOREIGN KEY (`intusuarioid`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblproduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblproduto` (
  `intprodutoid` INT(11) NOT NULL AUTO_INCREMENT,
  `intcategoriaid` INT(11) NOT NULL,
  `strproduto` VARCHAR(200) NOT NULL,
  `charunidade` CHAR(3) NOT NULL,
  `intestoque` INT(11) NULL,
  `strlote` VARCHAR(30) NULL DEFAULT NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`intprodutoid`),
  INDEX `idcategoria_idx` (`intcategoriaid` ASC) VISIBLE,
  CONSTRAINT `fk_prod_cat`
    FOREIGN KEY (`intcategoriaid`)
    REFERENCES `db_almoxarifado`.`tblcategoria` (`intcategoriaid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9330
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tbldetalhesentrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tbldetalhesentrada` (
  `intdetalhesentradaid` INT(11) NOT NULL AUTO_INCREMENT,
  `intnotaentradaid` INT(11) NOT NULL,
  `intprodutoid` INT(11) NOT NULL,
  `intquantidade` INT(11) NOT NULL,
  `dblvalor` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`intdetalhesentradaid`),
  INDEX `idproduto_idx` (`intprodutoid` ASC) VISIBLE,
  INDEX `fk_entrada_det_idx` (`intnotaentradaid` ASC) VISIBLE,
  CONSTRAINT `fk_entrada_det`
    FOREIGN KEY (`intnotaentradaid`)
    REFERENCES `db_almoxarifado`.`tblnotaentrada` (`intnotaentradaid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_det`
    FOREIGN KEY (`intprodutoid`)
    REFERENCES `db_almoxarifado`.`tblproduto` (`intprodutoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblposto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblposto` (
  `intpostoid` INT(11) NOT NULL AUTO_INCREMENT,
  `strposto` VARCHAR(45) NOT NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`intpostoid`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblpedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblpedido` (
  `intpedidoid` INT(11) NOT NULL AUTO_INCREMENT,
  `intusuarioid` INT(11) NOT NULL,
  `intpostoid` INT(11) NOT NULL,
  `intusuario_atendente` INT(11) NULL DEFAULT NULL,
  `datpedido` DATETIME NOT NULL,
  `datatendimento` DATETIME NULL DEFAULT NULL,
  `inttotal` INT(11) NOT NULL,
  `strobservacao` VARCHAR(255) NULL DEFAULT NULL,
  `strstatus` VARCHAR(40) NOT NULL DEFAULT 'REALIZADO',
  PRIMARY KEY (`intpedidoid`),
  INDEX `fk_pedido_posto_idx` (`intpostoid` ASC) VISIBLE,
  INDEX `fk_pedido_usuario_idx` (`intusuarioid` ASC) VISIBLE,
  INDEX `fk_pedido_atendente_idx` (`intusuario_atendente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_atendente`
    FOREIGN KEY (`intusuario_atendente`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_posto`
    FOREIGN KEY (`intpostoid`)
    REFERENCES `db_almoxarifado`.`tblposto` (`intpostoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_usuario`
    FOREIGN KEY (`intusuarioid`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tbldetalhespedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tbldetalhespedido` (
  `intdetalhespedidoid` INT(11) NOT NULL AUTO_INCREMENT,
  `intpedidoid` INT(11) NOT NULL,
  `intprodutoid` INT(11) NOT NULL,
  `intquantidade` INT(11) NOT NULL,
  `intqntentregue` INT(11) NULL DEFAULT NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`intdetalhespedidoid`),
  INDEX `fk_pedido_detalhes_idx` (`intpedidoid` ASC) VISIBLE,
  INDEX `fk_pedido_produto_idx` (`intprodutoid` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_detalhes`
    FOREIGN KEY (`intpedidoid`)
    REFERENCES `db_almoxarifado`.`tblpedido` (`intpedidoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_produto`
    FOREIGN KEY (`intprodutoid`)
    REFERENCES `db_almoxarifado`.`tblproduto` (`intprodutoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblpedidoepi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblpedidoepi` (
  `intpedidoepiid` INT(11) NOT NULL AUTO_INCREMENT,
  `intfuncionarioid` INT(11) NOT NULL,
  `intusuarioid` INT(11) NOT NULL,
  `intusuario_atendente` INT(11) NULL DEFAULT NULL,
  `datpedidoepi` DATETIME NOT NULL,
  `datatendimento` DATETIME NULL DEFAULT NULL,
  `strobservacao` VARCHAR(255) NULL DEFAULT NULL,
  `strstatus` VARCHAR(45) NOT NULL DEFAULT 'Aguardando Protocolo',
  PRIMARY KEY (`intpedidoepiid`),
  INDEX `fk_ped_epi_func_idx` (`intfuncionarioid` ASC) VISIBLE,
  INDEX `fk_ped_usuario_idx` (`intusuarioid` ASC) VISIBLE,
  INDEX `fk_pedidoepi_usuario_idx` (`intusuario_atendente` ASC) VISIBLE,
  CONSTRAINT `fk_ped_epi_func`
    FOREIGN KEY (`intfuncionarioid`)
    REFERENCES `db_almoxarifado`.`tblfuncionario` (`intfuncionarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ped_usuario`
    FOREIGN KEY (`intusuarioid`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidoepi_usuario`
    FOREIGN KEY (`intusuario_atendente`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tbldetalhespedidoepi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tbldetalhespedidoepi` (
  `intdetalhespedidoepiid` INT(11) NOT NULL AUTO_INCREMENT,
  `intpedidoepiid` INT(11) NOT NULL,
  `intprodutoid` INT(11) NOT NULL,
  `intquantidade` INT(11) NOT NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '1',
  `intqntentregue` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`intdetalhespedidoepiid`),
  INDEX `fk_det_ped_epi_idx` (`intpedidoepiid` ASC) VISIBLE,
  CONSTRAINT `fk_det_ped_epi`
    FOREIGN KEY (`intpedidoepiid`)
    REFERENCES `db_almoxarifado`.`tblpedidoepi` (`intpedidoepiid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblprotocolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblprotocolo` (
  `intprotocoloid` INT(11) NOT NULL AUTO_INCREMENT,
  `intpedidoepiid` INT(11) NOT NULL,
  `intfuncionarioid` INT(11) NOT NULL,
  `intusuarioid` INT(11) NOT NULL,
  `datprotocolo` DATETIME NOT NULL,
  `strobservacao` VARCHAR(255) NULL DEFAULT NULL,
  `strstatus` VARCHAR(40) NOT NULL DEFAULT 'Protocolo Aceito',
  PRIMARY KEY (`intprotocoloid`),
  INDEX `fk_func_protocolo_idx` (`intfuncionarioid` ASC) VISIBLE,
  INDEX `fk_usuario_protocolo_idx` (`intusuarioid` ASC) VISIBLE,
  INDEX `fk_pedidoepi_protocolo_idx` (`intpedidoepiid` ASC) VISIBLE,
  CONSTRAINT `fk_func_protocolo`
    FOREIGN KEY (`intfuncionarioid`)
    REFERENCES `db_almoxarifado`.`tblfuncionario` (`intfuncionarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidoepi_protocolo`
    FOREIGN KEY (`intpedidoepiid`)
    REFERENCES `db_almoxarifado`.`tblpedidoepi` (`intpedidoepiid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_protocolo`
    FOREIGN KEY (`intusuarioid`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 201
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tbldetalhesprotocolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tbldetalhesprotocolo` (
  `intdetalhesprotocoloid` INT(11) NOT NULL AUTO_INCREMENT,
  `intprotocoloid` INT(11) NOT NULL,
  `intprodutoid` INT(11) NOT NULL,
  `intpedidoepiid` INT(11) NULL DEFAULT NULL,
  `intqntautorizada` INT(11) NOT NULL,
  `bolestado` TINYINT(1) NULL DEFAULT '0',
  `bolsubstituicao` CHAR(2) NULL DEFAULT 'ND',
  PRIMARY KEY (`intdetalhesprotocoloid`),
  INDEX `fk_prod_protocolo_idx` (`intprodutoid` ASC) VISIBLE,
  INDEX `fk_protocolo_detalhes_idx` (`intprotocoloid` ASC) VISIBLE,
  INDEX `fk_protocolo_pedido_idx` (`intpedidoepiid` ASC) VISIBLE,
  CONSTRAINT `fk_prod_detalhes`
    FOREIGN KEY (`intprodutoid`)
    REFERENCES `db_almoxarifado`.`tblproduto` (`intprodutoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_protocolo_detalhes`
    FOREIGN KEY (`intprotocoloid`)
    REFERENCES `db_almoxarifado`.`tblprotocolo` (`intprotocoloid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 68
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblsetor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblsetor` (
  `intsetorid` INT(11) NOT NULL AUTO_INCREMENT,
  `strsetor` VARCHAR(45) NOT NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`intsetorid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblordemservico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblordemservico` (
  `intordemservicoid` INT(11) NOT NULL AUTO_INCREMENT,
  `intusuarioid` INT(11) NOT NULL,
  `intfornecedorid` INT(11) NOT NULL,
  `intcontatoid` INT(11) NOT NULL,
  `intsetorid` INT(11) NOT NULL,
  `strtiposervico` VARCHAR(20) NOT NULL,
  `datservico` DATE NOT NULL,
  `datgarantia` DATE NOT NULL,
  `dblvalor` DECIMAL(7,2) NOT NULL,
  `strservico` VARCHAR(255) NOT NULL,
  `charpagamento` CHAR(2) NOT NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`intordemservicoid`),
  INDEX `fk_ordemserv_forn_idx` (`intfornecedorid` ASC) VISIBLE,
  INDEX `fk_ordemserv_setor_idx` (`intsetorid` ASC) VISIBLE,
  INDEX `fk_ordemserv_contato_idx` (`intcontatoid` ASC) VISIBLE,
  INDEX `fk_ordemserv_usuario_idx` (`intusuarioid` ASC) VISIBLE,
  CONSTRAINT `fk_ordemserv_contato`
    FOREIGN KEY (`intcontatoid`)
    REFERENCES `db_almoxarifado`.`tblcontato` (`intcontatoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordemserv_forn`
    FOREIGN KEY (`intfornecedorid`)
    REFERENCES `db_almoxarifado`.`tblfornecedor` (`intfornecedorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordemserv_setor`
    FOREIGN KEY (`intsetorid`)
    REFERENCES `db_almoxarifado`.`tblsetor` (`intsetorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordemserv_usuario`
    FOREIGN KEY (`intusuarioid`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblservico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblservico` (
  `intservicoid` INT(11) NOT NULL AUTO_INCREMENT,
  `intcontatoid` INT(11) NOT NULL,
  `intusuarioid` INT NOT NULL,
  `intsetorid` INT NULL,
  `strtipo_servico` VARCHAR(45) NOT NULL,
  `datservico` DATETIME NOT NULL,
  `strdescricao` VARCHAR(255) NOT NULL,
  `datgarantia` DATE NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`intservicoid`),
  INDEX `fk_contato_servico_idx` (`intcontatoid` ASC) VISIBLE,
  INDEX `fk_posto_servico_idx` (`intsetorid` ASC) VISIBLE,
  INDEX `fk_users_servico_idx` (`intusuarioid` ASC) VISIBLE,
  CONSTRAINT `fk_contato_servico`
    FOREIGN KEY (`intcontatoid`)
    REFERENCES `db_almoxarifado`.`tblcontato` (`intcontatoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posto_servico`
    FOREIGN KEY (`intsetorid`)
    REFERENCES `db_almoxarifado`.`tblsetor` (`intsetorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_servico`
    FOREIGN KEY (`intusuarioid`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblnotaxml`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblnotaxml` (
  `intnotaxmlid` INT NOT NULL AUTO_INCREMENT,
  `strnomexml` VARCHAR(255) NOT NULL,
  `strcaminhoxml` VARCHAR(255) NOT NULL,
  `strextensao` VARCHAR(100) NOT NULL,
  `datenvioxml` TIMESTAMP NOT NULL,
  `inttamanho` INT NOT NULL,
  `intnumnota` INT NULL,
  `strnome_fornecedor` VARCHAR(255) NULL,
  `datemissao_nota` DATETIME NULL,
  `strnatureza_operacao` VARCHAR(100) NULL,
  `strcnpj_fornecedor` VARCHAR(18) NULL,
  `strendereco_fornecedor` VARCHAR(255) NULL,
  `strcep_fornecedor` VARCHAR(9) NULL,
  `strbairro_fornecedor` VARCHAR(100) NULL,
  `strcidade_fornecedor` VARCHAR(100) NULL,
  `charuf_fornecedor` MEDIUMTEXT NULL,
  `dblvalor_parcial` DECIMAL(7,2) NULL,
  `dblvalor_frete` DECIMAL(7,2) NULL,
  `dblvalor_desconto` DECIMAL(7,2) NULL,
  `dblvalor_total` DECIMAL(11,2) NULL,
  `strstatus` VARCHAR(20) NOT NULL DEFAULT 'Enviado',
  PRIMARY KEY (`intnotaxmlid`),
  UNIQUE INDEX `intnumnota_UNIQUE` (`intnumnota` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tbldetalhesnotaxml`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tbldetalhesnotaxml` (
  `intdetalhesnotaxmlid` INT NOT NULL AUTO_INCREMENT,
  `intnotaxmlid` INT NOT NULL,
  `intnumnota` INT NOT NULL,
  `intcodproduto` INT NOT NULL,
  `strnomeproduto` VARCHAR(255) NOT NULL,
  `charunidade` NCHAR(3) NOT NULL,
  `intquantidade_produto` INT NOT NULL,
  `dblvalor_produto` DECIMAL(7,2) NOT NULL,
  `dblvalortotal_produto` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`intdetalhesnotaxmlid`),
  INDEX `fk_intxmlid_notaxml_idx` (`intnotaxmlid` ASC) VISIBLE,
  CONSTRAINT `fk_intxmlid_notaxml`
    FOREIGN KEY (`intnotaxmlid`)
    REFERENCES `db_almoxarifado`.`tblnotaxml` (`intnotaxmlid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tbldevolucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tbldevolucao` (
  `intdevolucaoid` INT NOT NULL AUTO_INCREMENT,
  `datdevolucao` DATETIME NOT NULL,
  `intusuarioid` INT NOT NULL,
  PRIMARY KEY (`intdevolucaoid`),
  INDEX `fk_usuario_dev_idx` (`intusuarioid` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_dev`
    FOREIGN KEY (`intusuarioid`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_almoxarifado`.`tblcontrole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_almoxarifado`.`tblcontrole` (
  `intcontroleid` INT NOT NULL AUTO_INCREMENT,
  `intfuncionarioid` INT NOT NULL,
  `intpostoid` INT NOT NULL,
  `intusuarioid` INT NOT NULL,
  `intusuario_validacao` INT NULL,
  `datinicial` DATETIME NOT NULL,
  `datfinal` DATETIME NOT NULL,
  `intapto` INT NOT NULL,
  `strobservacao` VARCHAR(255) NULL,
  `bolstatus` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`intcontroleid`),
  INDEX `fk_func_controle_idx` (`intfuncionarioid` ASC) VISIBLE,
  INDEX `fk_posto_controle_idx` (`intpostoid` ASC) VISIBLE,
  INDEX `fk_users_controle_idx` (`intusuarioid` ASC) VISIBLE,
  INDEX `fk_users_validacao_idx` (`intusuario_validacao` ASC) VISIBLE,
  CONSTRAINT `fk_func_controle`
    FOREIGN KEY (`intfuncionarioid`)
    REFERENCES `db_almoxarifado`.`tblfuncionario` (`intfuncionarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posto_controle`
    FOREIGN KEY (`intpostoid`)
    REFERENCES `db_almoxarifado`.`tblposto` (`intpostoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_controle`
    FOREIGN KEY (`intusuarioid`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_validacao`
    FOREIGN KEY (`intusuario_validacao`)
    REFERENCES `db_almoxarifado`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
